#ifndef _IOCTL_H_
#define _IOCTL_H_

#ifdef _MYDRV_H_
#include "devioctl.h"
#else
#include "winioctl.h"
#endif

#define MYDRV_IOCTL_EVENT1		CTL_CODE(FILE_DEVICE_UNKNOWN, 0x0, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define MYDRV_IOCTL_EVENT2		CTL_CODE(FILE_DEVICE_UNKNOWN, 0x1, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define MYDRV_IOCTL_MUTEX1		CTL_CODE(FILE_DEVICE_UNKNOWN, 0x2, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define MYDRV_IOCTL_MUTEX2		CTL_CODE(FILE_DEVICE_UNKNOWN, 0x3, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define MYDRV_IOCTL_ERESOURCE1	CTL_CODE(FILE_DEVICE_UNKNOWN, 0x4, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define MYDRV_IOCTL_ERESOURCE2	CTL_CODE(FILE_DEVICE_UNKNOWN, 0x5, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define MYDRV_IOCTL_IOVERIFY	CTL_CODE(FILE_DEVICE_UNKNOWN, 0x6, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define MYDRV_IOCTL_BREAKPOINT	CTL_CODE(FILE_DEVICE_UNKNOWN, 0x7, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define MYDRV_IOCTL_HANG		CTL_CODE(FILE_DEVICE_UNKNOWN, 0x8, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define MYDRV_IOCTL_BUGCHECK_0xA	CTL_CODE(FILE_DEVICE_UNKNOWN, 0x10, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define MYDRV_IOCTL_BUGCHECK_0x1E	CTL_CODE(FILE_DEVICE_UNKNOWN, 0x11, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define MYDRV_IOCTL_BUGCHECK_0x50	CTL_CODE(FILE_DEVICE_UNKNOWN, 0x12, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define MYDRV_IOCTL_BUGCHECK_0x7F	CTL_CODE(FILE_DEVICE_UNKNOWN, 0x13, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define MYDRV_IOCTL_BUGCHECK_0x3B	CTL_CODE(FILE_DEVICE_UNKNOWN, 0x14, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define MYDRV_IOCTL_BUGCHECK_0xBE	CTL_CODE(FILE_DEVICE_UNKNOWN, 0x15, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define MYDRV_IOCTL_BUGCHECK_0xC4	CTL_CODE(FILE_DEVICE_UNKNOWN, 0x16, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define MYDRV_IOCTL_BUGCHECK_0xD6	CTL_CODE(FILE_DEVICE_UNKNOWN, 0x17, METHOD_BUFFERED, FILE_ANY_ACCESS)

#endif // _IOCTL_H_
